#pragma once
#include "CoreMinimal.h"
#include "EDramaTrackBoneId.generated.h"

UENUM(BlueprintType)
enum class EDramaTrackBoneId : uint8 {
    core,
    mune1,
    mune2,
    koshi,
    kubi,
    atama,
    sakotsu_r,
    kata_r,
    ude_r,
    te_r,
    sakotsu_l,
    kata_l,
    ude_l,
    te_l,
    momo_r,
    sune_r,
    ashi_r,
    momo_l,
    sune_l,
    ashi_l,
    tsumasaki_r,
    tsumasaki_l,
    atama_top,
    ashi_bottom_r,
    ashi_bottom_l,
    tsumasaki_bottom_r,
    tsumasaki_bottom_l,
    atama_new,
    kubi_new,
    null_hit = 30,
    senaka,
    senaka2,
    koshi_sp,
    koshi_sp2,
    hitai,
    te_r_hi,
    te_r_lo,
    te_l_hi,
    te_l_lo,
    te_r_hi7,
    te_r_lo7,
    te_l_hi7,
    te_l_lo7,
    lee_ashi_l,
    lee_ashi_r,
    ashi_jp_l,
    ashi_jp_r,
    ashi_l_hi,
    ashi_r_hi,
    rog_te_l,
    rog_te_r,
    hizi_l_lo,
    hizi_r_lo,
    ashi_jp_l2,
    ashi_jp_r2,
    katana = 61,
    katanaS,
    katanaR,
    kuma_hip,
    tail,
    frvKatana = 68,
    fire = 77,
    fire2,
    fire3,
    laser,
    poison = laser,
    poison2 = laser,
    poison3 = laser,
    poison4 = laser,
    chainsaw_l,
    chainsaw_r,
    kunai1,
    kunai2,
    kunai3,
    item1,
    item2,
    item3,
    ithave_l2em4,
    mrzLSword_l = 94,
    mrzSword_l,
    mrzDagger_l,
    mrzShield,
    mrzLSword_r,
    mrzSword_r,
    mrzDagger_r,
    mrzSpear,
    mrzSwordHandle_r,
    mrzKingLSword_r,
    mrzLSwordHandle_r,
    mrzDadSword_r,
    nsaLucilleS_l,
    nsaLucilleN_l,
    nsaLucilleL_l,
    nsaLucilleB_l,
    nsaKnife_l,
    nsaLucilleS_r,
    nsaLucilleN_r,
    nsaLucilleL_r,
    nsaLucilleB_r,
    nsbFolding,
    knmShortSword_l,
    knmShortSword_r,
    knmNinjaKnife,
    knmNinjaKnifeHandle,
    have_l,
    have_r,
    koshi_sp3 = 188,
    qt_az_te_l,
    qt_az_te_r,
    qt_az_te_l_lo,
    qt_az_te_r_lo,
    te_ashi_sp_ctrl = core,
    have_l2 = 126,
    have_r2,
};

