#pragma once
#include "CoreMinimal.h"
#include "EGeneralBattleEvent.generated.h"

UENUM(BlueprintType)
enum class EGeneralBattleEvent : uint8 {
    None,
    PreStart_1P,
    PreStart_2P,
    PreStart_Fate,
    FIGHT,
    FIGHT_Fate,
    FIGHT_Mid,
    FIGHT_Last,
    BattleFinish,
    BattleFinish_Last,
    Win,
    WallHit,
    WallHitS,
    BigDamage,
    RageArts,
    SuperSlow,
    ZoneStart,
    ZoneEnd,
    ZoneEndEffect,
    DevilEndEffect,
    NoticeStageDestruction,
    FloorBreak0,
    FloorBreak1,
    FloorBreak2,
    FloorBreak3,
    FloorBreak4,
    ROUNDN,
    ZoneBegin,
    FloorHitS,
    StageUniq0,
    StageUniq1,
    StageUniq2,
    ROUND1,
    ROUND_OTHER,
    WallBreak,
    FightOnStageDestruction,
    ROUND_ODD,
    ROUND_EVEN,
    ROUND1_Practice,
    DemoSkip,
    Max,
};

