#pragma once
#include "CoreMinimal.h"
#include "EPolarisEffectVertexClutId.generated.h"

UENUM(BlueprintType)
enum class EPolarisEffectVertexClutId : uint8 {
    POLARIS_OEF_CL_RED,
    POLARIS_OEF_CL_ORANGE,
    POLARIS_OEF_CL_YELLOW,
    POLARIS_OEF_CL_LIME,
    POLARIS_OEF_CL_GREEN,
    POLARIS_OEF_CL_EMERALD,
    POLARIS_OEF_CL_CYAN,
    POLARIS_OEF_CL_SKYBLUE,
    POLARIS_OEF_CL_BLUE,
    POLARIS_OEF_CL_PURPLE,
    POLARIS_OEF_CL_MAGENTA,
    POLARIS_OEF_CL_ROSE,
    POLARIS_OEF_CL_WHITE,
    POLARIS_OEF_CL_TEX,
    POLARIS_OEF_CL_WHITE2,
    POLARIS_OEF_CL_SPECIAL2,
    POLARIS_OEF_CL_SPECIAL1,
    POLARIS_OEF_CL_SRC,
    POLARIS_OEF_CL_AUTO,
    POLARIS_OEF_CL_VERTEX,
    POLARIS_OEF_CL_SCA,
    POLARIS_OEF_CL_SCB,
    POLARIS_OEF_CL_SCC,
};

